version: '3.3'
services:

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: eeyeppr/bake-at-dome-nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - mongo-net

  backend:
    restart: on-failure
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: eeyeppr/bake-at-dome-backend
    container_name: backend
    volumes:
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/BakeAtDome
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - mongo-net

  frontend:
    restart: on-failure
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: eeyeppr/bake-at-dome-frontend
    container_name: frontend
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mongo-net

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mongo-net
    volumes:
      - mongo-data:/data/db

  cypress:
    image: cypress/included:3.8.3
    container_name: cypress
    volumes:
      - ./cypress:/e2e
    working_dir: /frontend/cypress/e2e
    command: ["npm", "run", "cypress:run"]
    depends_on:
      - backend
      - frontend
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge
volumes:
  mongo-data:
    driver: local