name: BakeAtDome

on:
  push:
    branches: [ Dev-Eye ]
  pull_request:
    types: [ opened, reopened, closed, edited ]
  merge_group:
    types: [checks_requested]
    branches: [ Dev-Eye ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        
    - name: Install dependencies backend
      working-directory: ./backend
      run: npm install --legacy-peer-deps

    - name: Install dependencies frontend
      working-directory: ./frontend
      run: npm install --legacy-peer-deps

    - name: Start backend
      working-directory: ./backend
      run: npm run server
      
    - name: Start frontend
      working-directory: ./frontend
      run: npm start

    - name: Test backend
      working-directory: ./backend
      run: npm run test

    - name: Test frontend
      working-directory: ./frontend
      run: npm run test:protractor

      
  build:
    if: ${{ always() }}
    needs: [ test ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to DockerHub
      if: success()
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bake-at-dome-image:latest
  
  # deploy:
  #   if: ${{ always() }}
  #   needs: [ build ]
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Configure AWS credentials
  #     if: success()
  #     uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
  #       aws-region: ${{ secrets.AWS_REGION }}
 
  #   - name: Create EC2 and deploy application to EC2
  #     if: success()
  #     env: 
  #       KEY_PAIR_NAME: ${{ secrets.AWS_KEYPAIR_NAME }}
  #       SECGROUP_ID: ${{ secrets.AWS_SECGROUP_ID }}
  #     run: aws ec2 run-instances --image-id ami-04902260ca3d33422 --instance-type t2.micro  --key-name $KEY_PAIR_NAME --security-group-ids $SECGROUP_ID

  # test:
  #   if: ${{ always() }}
  #   needs: [ build ]

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: install Docker client
  #     run: |
  #       sudo apt-get update
  #       sudo apt-get -y install --no-install-recommends docker.io
  #   - name: Run docker
  #     uses: addnab/docker-run-action@v3
  #     with:
  #       image: ${{ secrets.DOCKER_USERNAME }}/bake-at-dome:${{ github.run_number }}
  #       run: docker run ${{ secrets.DOCKER_USERNAME }}/bake-at-dome:${{ github.run_number }}
  #   - name: show running containers
  #     run: docker ps

  #   - name: Test backend
  #     working-directory: ./app/backend
  #     run: npm run test

  #   - name: Test frontend
  #     working-directory: ./app/frontend
  #     run: npm run test:protractor
